Rename disable dhcpcd to june2017_patch, include branding update, more time before reboot

diff --git a/octoprint_lui/system_scripts/june2017_patch b/octoprint_lui/system_scripts/june2017_patch
--- a/octoprint_lui/system_scripts/june2017_patch
+++ b/octoprint_lui/system_scripts/june2017_patch
@@ -2,11 +2,14 @@
 
 ###
 #
-# This script purges dhcpcd as it conflicts with setting
+# This script patches v1.0 and v1.1 lpfrg images.
+# The script purges dhcpcd as it conflicts with setting
 # a static IP address trough NetworkManager. For image v1.0
 # the purge is executed immediately. For v1.1, the script
 # makes root writable, reboots, purges dhcpcd, makes root ro again
-# and reboots again. For >= v1.2, does nothing.
+# and reboots again. Besides the dhcpcd purge, the branding images 
+# are updated and the NetworkManager state folder is moved
+# to the writable home partition.
 #
 ###
 
@@ -14,19 +17,30 @@ source_nm_state_dir="/var/lib/NetworkManager"
 target_nm_state_dir="/home/etc/NetworkManager/state"
 autostart="/home/pi/.config/openbox/autostart"
 imageinfo="/boot/lpfrgpi.json"
+branding_file="/home/pi/.branding_june2017"
+
+run_sequence()
+{
+    do_update_branding
+    do_disable_dhcpcd
+    do_move_nm_state
+}
+
+splash()
+{
+    feh --bg-max /home/pi/scripts/images/lpfrg-updates.png &
+}
 
 do_start()
 {
-    if  ! dhcpcd_installed && state_writable ; then
-        echo "Dhcpcd not found. State already writable. Nothing to do."
+    if  ! dhcpcd_installed && state_writable && branding_updated ; then
+        echo "Dhcpcd not found. State already writable. Branding updated. Nothing to do."
         exit 0
     elif [ ! -f "$imageinfo" ]; then
         # No image info, we are < v1.1
-        echo "Image version < 1.1, going to purge dhcpcd"
-        do_disable_dhcpcd
-        echo "Purging done. Moving NM state folder..."
-        do_move_nm_state
-        echo "Folder moved. Please reboot."
+        echo "Image version < 1.1, going to run patch sequence"
+        run_sequence
+        echo "Done. Please reboot."
         exit 3
     elif grep -q "\"image_version\"\: \"1.1.0\"" "$imageinfo"; then
         # V1.1
@@ -61,9 +75,9 @@ do_uninstall() {
     sudo sed -i '/disable_dhcpcd/d' "$autostart"
 
     # Makes root read-writable again on next reboot
-	if ! grep -q "boot=overlay" /boot/cmdline.txt ; then
-		sudo sed -i '1s@^@boot=overlay @' /boot/cmdline.txt
-	fi
+    if ! grep -q "boot=overlay" /boot/cmdline.txt ; then
+        sudo sed -i '1s@^@boot=overlay @' /boot/cmdline.txt
+    fi
 
     sudo sed -i "s@root_readonly=\"no\"@root_readonly=\"yes\"@" /boot/octopi.txt
 
@@ -85,11 +99,11 @@ do_move_nm_state() {
 
         if [ -d "$source_nm_state_dir" ]; then
             sudo rm -r "$source_nm_state_dir"
-			echo "Old state folder deleted."
+            echo "Old state folder deleted."
         fi
 
         sudo ln -s "$target_nm_state_dir" "$source_nm_state_dir"
-		echo "State folder link created."
+        echo "State folder link created."
         
     else
         echo "State folder was already writable."
@@ -105,12 +119,55 @@ do_disable_dhcpcd() {
     fi
 }
 
+do_update_branding() {
+	
+	if branding_updated; then
+		echo "Branding already updated"
+	else
+
+		echo "Copying images..."
+		sudo cp -f /home/pi/scripts/images/splash-portrait.png /home/pi/lpfrg-portrait.png
+
+		if [ -f "/etc/lilybootportrait.png" ]; then
+			sudo cp -f /home/pi/scripts/images/splash-portrait.png /etc/lilybootportrait.png
+			sudo cp -f /home/pi/scripts/images/splash-shutdown-portrait.png /etc/lilyshutdownportrait.png
+		fi
+		
+		if [ -d "/usr/share/plymouth/themes/lpfrg/" ]; then
+
+			sudo cp -f /home/pi/scripts/images/splash-portrait.png /usr/share/plymouth/themes/lpfrg/splash-portrait.png
+			sudo cp -f /home/pi/scripts/images/splash-shutdown-portrait.png /usr/share/plymouth/themes/lpfrg/splash-shutdown-portrait.png
+
+			echo "Updating initramfs..."
+
+			kernelv=$(uname -r)
+			update-initramfs -c -k $kernelv
+
+		fi
+
+		touch "$branding_file"
+		echo "Done."
+
+	fi
+}
+
+branding_updated() {
+	if [ -f "$branding_file" ]; then
+		return 0
+	else
+		return 1
+	fi
+}
+
 dhcpcd_installed() {
     dpkg -l | grep -q "dhcpcd"
 }
 
 state_writable() {
-    if [[ -L "$source_nm_state_dir" ]] && [[ -d "$target_nm_state_dir" ]]; then
+    if [ ! -d "/home/etc/NetworkManager" ]; then
+		# If we don't have this folder, we are prior to v1.1. Root is writable.
+        return 0
+    elif [[ -L "$source_nm_state_dir" ]] && [[ -d "$target_nm_state_dir" ]]; then
         return 0
     else
         return 1
@@ -121,9 +178,9 @@ key="$1"
 
 case $key in
     "run")
-    do_disable_dhcpcd
-    do_move_nm_state
-    do_uninstall
+    splash
+    run_sequence
+	do_uninstall
     sudo reboot
     ;;
 
